
export const products = [
    {
      "name": "Oxy Fizz",
      "price": "19.99",
      "image_url": "OxyFizz.jpeg",
      "description": "Sparkle up your space with Oxy Fizz, a fizzy burst of pure, oxygen-rich air. This delightful concoction not only rejuvenates your senses but also infuses your surroundings with a lively, effervescent ambiance, leaving you refreshed and revitalized.",
      "country_of_origin": "Spain",
    },
    {
      "Products": "International Air",
      "price": "24.50",
      "image_url": "InternationalAir.jpeg",
      "description": "Embark on a global olfactory journey with International Air, a collection of scents inspired by the world's most captivating destinations. From the tranquil beaches to the bustling cityscapes, each can encapsulates the essence of a different corner of the globe.",
      "country_of_origin": "US",
    },
    {
      "Products": "AirTastic",
      "price": "21.99",
      "image_url": "AirTastic.jpeg",
      "description": "Transform your space into a haven of freshness with AirTastic, where each can releases a burst of revitalizing energy. Whether it's for a quick refresh or to set the mood, AirTastic brings a touch of magic to your environment.",
      "country_of_origin": "Japan",
    },
    {
      "Products": "Inteligent Air",
      "price": "32.99",
      "image_url": "InteligentAir.jpeg",
      "description": "Raise the bar on your surroundings with Inteligent Air, a smart choice for a refreshing atmosphere. Its advanced formulation not only purifies the air but also revitalizes your senses, making it perfect for any workspace or environment.",
      "country_of_origin": "Germany",
    },
    {
      "Products": "Air Pure",
      "price": "28.50",
      "image_url": "AirPure1.jpeg",
      "description": "AirPure offers a range of canned air products designed to bring the rejuvenating essence of nature to your space. From mountain breezes to coastal serenity, each can is a breath of fresh air.",
      "country_of_origin": "Japan",
    },
    {
      "Products": "EcoVapor",
      "price": "26.50",
      "image_url": "EcoVapor.jpeg",
      "description": "EcoVapor specializes in eco-friendly canned air, providing a selection of scents inspired by the world's most breathtaking natural environments. Elevate your surroundings with our sustainable air solutions.",
      "country_of_origin": "China",
    },
    {
      "Products": "AzroZen",
      "price": "34.99",
      "image_url": "AzroZen.jpeg",
      "description": "AzroZen invites you on a sensory journey to find your zen with our calming and uplifting canned air. Experience the serenity of zen gardens or the calmness of a wilderness retreat, all at your fingertips.",
      "country_of_origin": "China",
    },
    {
      "Products": "Arctic Aura",
      "price": "39.99",
      "image_url": "ArticAura.jpeg",
      "description": "ArcticAura brings the crisp, invigorating air of the polar regions directly to you. Experience the purity and revitalizing effects of the Arctic every single day.",
      "country_of_origin": "Canada",
    },
    {
      "Products": "Tropicool",
      "price": "25.99",
      "image_url": "Tropicool.jpeg",
      "description": "TropiCool offers a vacation in a can! Immerse yourself in the soothing scents of tropical paradises, complete with the gentle rustle of palm leaves and the kiss of ocean breezes.",
      "country_of_origin": "Cuba",
    },
    {
      "Products": "Mystic Air",
      "price": "27.25",
      "image_url": "MysticAir.jpeg",
      "description": "Transport yourself to mystical realms with Mystic Air's enchanting canned air. From ancient forests to cosmic wonders, each can holds a unique olfactory adventure waiting to be explored.",
      "country_of_origin": "Japan",
    },
    {
      "Products": "Sky Scent",
      "price": "28.50",
      "image_url": "SkyScent1.jpeg",
      "description": "The freshest air comes from where the sky meets the earth. SkyScent harnesses the invigorating air of the clouds and provides fresh inspiration for those brave enough to reach for the sky.",
      "country_of_origin": "Canada",
    },
    {
      "Products": "Elevation",
      "price": "31.99",
      "image_url": "Elevation.jpeg",
      "description": "Inspired by the purest mountain breezes, Elevation brings the crisp, refreshing essence of high altitudes to your space. For a quick pick-me-up or creating a focused atmosphere reach for Elevation and Elevate your senses.",
      "country_of_origin": "Germany",
    },
    {
      "Products": "Pirisiine Air",
      "price": "24.99",
      "image_url": "PirisiineAir.jpeg",
      "description": "Experience the invigorating aroma of Pirisiine Air, a breath of pristine nature captured in a can. Immerse yourself in the essence of untouched forests and pure mountain peaks, revitalizing your space with every spray.",
      "country_of_origin": "Turkey",
    },
    {
      "Products": "Nebula",
      "price": "35.99",
      "image_url": "Nebula.jpeg",
      "description": "Explore the cosmos with Nebula. Our canned air blends capture the awe-inspiring essence of distant nebulae, providing a truly celestial olfactory experience.",
      "country_of_origin": "US",
    },
    {
      "Products": "Oasis Air",
      "price": "36.75",
      "image_url": "Oasis.jpeg",
      "description": "Create your own personal oasis with Oasis Air. Our cans offer the purest, cleanest air to refresh your environment, making it perfect to aid in your daily relaxation and meditation.",
      "country_of_origin": "US",
    },
    {
      "Products": "Breezy Bliss",
      "price": "33.99",
      "image_url": "BreezyBliss.jpeg",
      "description": "Follow your Bliss and find your beach. The fresh, breezy airs of tropical paradise await with each can of Breezy Bliss. When you’re feeling stress let the breezes of the tropics help you find your bliss.",
      "country_of_origin": "Spain",
    },
   ];
